---
title: "Das Schwerpunktfach Wirtschaft und Recht muss erhalten bleiben"
---

***Der Kanton Zürich will an seinen Gymnasien das Schwerpunktfach
Wirtschaft und Recht abschaffen.***

*Das bisherige Schwerpunktfach Wirtschaft und Recht soll neu in einem
hybriden Fach aus Geschichte und/oder Geographie sowie Wirtschaft und
Recht aufgehen.*

## Folgen der Abschaffung des Schwerpunktfachs Wirtschaft und Recht

Im bisherigen Schwerpunktfach Wirtschaft und Recht wird
Betriebswirtschaftslehre, Finanz- und Rechnungswesen,
Volkswirtschaftslehre sowie Recht unterrichtet. In der neuen
Ausgestaltung müsste auf Finanz- und Rechnungswesen sowie auf erhebliche
Teile der Betriebswirtschaftslehre verzichtet werden. 
Im Recht müsste zum Beispiel auf lebens- und gesellschaftsrelevante
Themen wie Miet- oder Arbeitsrechte verzichtet werden.

## Wie ist es soweit gekommen?

Per 1. August 2024 ist die neue Maturitätsanerkennungsverordnung (MAV)
in Kraft getreten. Die Revision der MAV durch Bund und Kantone erfordert
Anpassungen in der Ausgestaltung der Gymnasien in den Kantonen.

Die Revision der MAV hat dem interdisziplinären Arbeiten einen grösseren
Stellenwert eingeräumt. Mindestens 3% der Unterrichtszeit müssen dafür
aufgewendet werden. Der Kanton Zürich hat sich als einziger Kanton dafür
entschieden, dieses Ziel durch die Ausgestaltung der Schwerpunktfächer
zu erreichen. Ausserdem hat der Kanton Zürich interdisziplinäres
Arbeiten als das Unterrichten durch zwei Lehrpersonen mit einer
Lehrberechtigung in zwei verschiedenen Fächern definiert. Das bedeutet,
dass das bisherige Schwerpunktfach Wirtschaft und Recht in seiner
aktuellen Form den Ansprüchen nicht mehr genügt und nicht mehr angeboten
werden darf. Dies obwohl 
Wirtschaft und Recht unter der alten MAV das einzige interdisziplinäre
Schwerpunktfach war.

## Warum braucht es neben dem Grundlagenfach das Schwerpunktfach?

Die Revision der MAV schafft ein zwingendes Grundlagenfach Wirtschaft
und Recht. Alle Gymnasiastinnen und Gymnasiasten müssen dieses Fach im
Umfang von vier Jahreslektionen besuchen[^1]. Das ist ein wichtiger Beitrag
zur Allgemeinbildung und zu begrüssen. Allerdings ist festzuhalten, dass
mit dieser Stundendotation bestenfalls an der Oberfläche gekratzt
werden kann. Der Status als Grundlagenfach bedeutet lediglich, dass das
Fach eine Maturnote erhält. Es hat aber niemals die gleiche Bedeutung
wie beispielsweise die Fächer Mathematik oder Deutsch.

Wer sich in volkswirtschaftliche, betriebswirtschaftliche und 
finanzwirtschaftliche Zusammenhänge, unternehmerisches Denken oder
rechtliche Fragen vertieften will, braucht ein Schwerpunktfach Wirtschaft und
Recht.

## Auswirkungen auf die Schullandschaft

Für die kleinen spezialisierten Gymnasien, wie zum Beispiel die Kantonsschule Büelrain in
Winterthur oder die Kantonsschule Hottingen in Zürich, bedeutet dies den
Verlust ihrer Identität und allenfalls ihrer Eigenständigkeit. 

Wir fordern daher die Beibehaltung des Schwerpunktfachs Wirtschaft und Recht in seiner
aktuellen Form.

## Weiterführende Links

* [Ausgangslage auf Stufe Bund](https://www.edk.ch/de/die-edk/news/20240731)
* [Umsetzungsprojekt der Vorgaben des Bundes im Kanton Zürich](https://www.zh.ch/de/bildung/schulen/maturitaetsschule/projekte-maturitaetsschulen/gemeinsam-die-zukunft-der-gymnasien-gestalten.html)
* [Antrag der Bildungsdirektion an den Bildungsrat](https://www.zh.ch/de/bildungsdirektion/generalsekretariat-der-bildungsdirektion/bildungsrat/suche-bildungsratsbeschluesse/2024-brb-05.html)
* [‘Die Volkswirtschaft’ zur Stundendotation im Fach Wirtschaft und Recht](https://dievolkswirtschaft.ch/de/2025/06/wirtschaft-und-recht-als-maturitaetsfach-fuer-alle/)
* [Tagesanzeiger - Der Kanton ändert die Schwerpunktfächer an den Gymnasien radikal](https://www.tagesanzeiger.ch/gymnasium-zuerich-das-sind-die-zwoelf-neuen-schwerpunktfaecher-412150645711?utm_source=chatgpt.com)

## Ich unterstützte den Erhalt des Schwerpunktfachs Wirtschaft und Recht

Wenn Sie die Beibehaltung des Schwerpunktftaches Wirtschaft und Recht
mit Ihrem Namen unterstützen wollen, können Sie sich 
<a href="https://forms.gle/Qii7X7os3id8N1qK8" target="_blank">hier</a>
eintragen.

[^1]: Vier Jahreslektionen bedeutet, dass beispielsweise entweder
    während vier Jahren wöchentlich eine Lektion oder während
    zwei Jahren wöchentlich zwei Lektionen stattfinden.
